#:schema node_modules/wrangler/config-schema.json
name = "zhq"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "d638b15a09474a2d80102c15862d79f4" }
]
